name: VarOS Container Image

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'build_files/**'
      - '.github/workflows/build.yml'

  schedule:
    - cron: '05 10 * * *'

  workflow_dispatch:

env:
  IMAGE_DESC: 'My Customized Bazzite Image called VarOS'
  IMAGE_KEYWORDS: 'bootc,ublue,universal-blue'
  IMAGE_LOGO_URL: 'https://avatars.githubusercontent.com/u/120078124?s=200&v=4'

  IMAGE_NAME: '${{ github.event.repository.name }}'
  IMAGE_REGISTRY: 'ghcr.io/${{ github.repository_owner }}'

  DEFAULT_TAG: 'latest'
  FEDORA_VERSION: '44'

concurrency:
  group: varos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@main

      #
      # Proper Buildah storage caching
      #
      - name: Restore container storage
        uses: ublue-os/container-storage-action@main
        with:
          storage-path: /var/lib/containers/storage
          save-cache: false

      - name: Get current date
        id: date
        run: |
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }}
            type=raw,value={{date 'YYYYMMDD'}}
            type=sha,enable=${{ github.event_name == 'pull_request' }}

          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            containers.bootc=1

      - name: Build Image
        id: build_image
        env:
          LABELS: ${{ steps.metadata.outputs.labels }}
        run: |
          echo "$LABELS" > /tmp/image-labels.txt

          LABEL_ARGS=()

          while IFS= read -r label; do
            [ -z "$label" ] && continue
            LABEL_ARGS+=(--label "$label")
          done < /tmp/image-labels.txt

          sudo -E buildah build \
            "${LABEL_ARGS[@]}" \
            --layers \
            --tag raw-img \
            .

      - name: Rechunk image
        id: rechunk
        run: |
          container=$(sudo buildah from raw-img)
          mnt=$(sudo buildah mount $container)

          sudo rm -rf \
            "$mnt/run/"* \
            "$mnt/tmp/"*

          sudo buildah umount $container

          sudo buildah commit \
            --identity-label=false \
            --rm \
            $container \
            raw-img

          sudo podman run --rm --privileged \
            -v /var/lib/containers:/var/lib/containers \
            -v /var/tmp:/var/tmp \
            localhost/raw-img \
            rpm-ostree compose build-chunked-oci \
              --bootc \
              --max-layers 127 \
              --format-version 2 \
              --from localhost/raw-img \
              --output containers-storage:localhost/chunked-img

          echo "ref=containers-storage:localhost/chunked-img" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            sudo skopeo login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin

          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin

      - name: Push image
        id: push
        if: github.event_name != 'pull_request'
        env:
          IMAGE_REF: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          RECHUNK_REF: ${{ steps.rechunk.outputs.ref }}
        run: |
          sudo skopeo copy \
            ${RECHUNK_REF} \
            docker://${IMAGE_REF}:${{ env.DEFAULT_TAG }}

          DIGEST=$(sudo skopeo inspect \
            --format '{{.Digest}}' \
            docker://${IMAGE_REF}:${{ env.DEFAULT_TAG }})

          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Save container storage
        if: github.event_name != 'pull_request'
        uses: ublue-os/container-storage-action@main
        with:
          storage-path: /var/lib/containers/storage
          save-cache: true

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4
        with:
          cosign-release: 'v2.6.1'

      - name: Sign image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          cosign sign -y \
            --key env://COSIGN_PRIVATE_KEY \
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}
